### ISSUE TITLE
again?

### ISSUE THREAD

**Issue by BlazeTBV** [BeastlyGhost/Forever-Engine-Feather#1]
why

**Comment by BeastlyGhost** [comment]
i was unhappy with how things were being done before

**Comment by BlazeTBV** [comment]
> i was unhappy with how things were being done before

It was so good tho lol. your choice ig but i think some stuff like the credits menu would be good to be reused
like its so much better t han psych's

**Comment by BeastlyGhost** [comment]
> > i was unhappy with how things were being done before
> 
> It was so good tho lol. your choice ig but i think some stuff like the credits menu would be good to be reused like its so much better t han psych's

there's stuff that is already being reused such as the Prepare sprite, but i'm gonna focus on the core stuffs first (e.g: Scripts, Notetypes, etc)

**Comment by BlazeTBV** [comment]
you should  totally add lua or something
