### ISSUE TITLE
Question: What is Funkin Cocoa?

### ISSUE THREAD

**Issue by MemeHoovy** [BeastlyGhost/Forever-Engine-Feather#12]
I've seen it here
https://github.com/BeastlyGhost/Forever-Engine-Feather/blob/master/source/gameObjects/Character.hx#L19
But idk what it is, is it like an old engine or something?
Kinda wish there was also an question issue template aswell

**Comment by BeastlyGhost** [comment]
a work in progress engine made by a friend, it's currently a work in progress and the character format for it (which uses yaml) hasn't been implemented yet

**Comment by MemeHoovy** [comment]
kay great, thanks
