### ISSUE TITLE
Small Discord Server [REQUEST]

### ISSUE THREAD

**Issue by BlueColorsin** [BeastlyGhost/Forever-Engine-Feather#22]
In summery Psych Discord Server but more simple for feather lol

[Recommended Priority] low (after modpacks)

in detail
F.E.Feather has an complex structure for scripting and a little bit ago had a soft coded menustate until the (lots of stuff) commit
it also has a more unique soft coding format, so a discord server would be useful for both sharing info on how fe would work 
instead of needing to make and issue page for it in github you can just make a forms in the discord so the issues page in github
can be a issues page

this will also allow you to build up a community, I say this would be good for fe feather due to the fact AFTER you add modpacks so 
people can share project files and ports/scripts forks and a shit ton more. 
you would be able to show little teasers of what you are planning on doing 
and get more suggestions on what to add and how to add them
plus you can make polls for people to chose what should be added or removed

Main Problem 
Moderation is a ass pain for discord 
so I just suggest making it a small server with at least these channels

-----
1 [Rules] {for telling the people what to do}
2 [Announcements] {could communicate with your fans by threads or forms or by yes/no poles}
3 [GitHub Updates] -github bot
4 [Joined] -{not needed but recomended}-
5 [starboard] -carl bot {for the community aspect}
-----
6 [General] {kinda self explanatory}
7 [Showcase]
8 [Media]
-----
9 [Scripts-Downloads] -{forms}- {for the community aspect}
10 [Feather General] {main talking place for fe feather ofc}
11 [Feather Showcase] {Showcase Scripts and such}
12 [Feather-Help] -forms- {for the community aspect}
13[Feather-Suggestions] -{Forms/Channel}- {both will work}
-----
VC channels will not be necessary but 1 or 2 will work 
-----

kinda meant psych discord but more simple lol

**Comment by BlazeTBV** [comment]
it exists

**Comment by BlueColorsin** [comment]
Thanks 
should probably put it on the github lol
