### ISSUE TITLE
[HELP] COMPILATION

### ISSUE THREAD

**Issue by BlazeTBV** [BeastlyGhost/Forever-Engine-Feather#23]
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:94: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:142: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:150: characters 18-19 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:151: characters 18-19 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:413: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:419: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:420: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:423: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:424: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:426: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:427: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:429: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:429: characters 44-45 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:430: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:430: characters 44-45 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:450: characters 20-21 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:456: characters 20-21 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:493: characters 30-31 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:494: characters 30-31 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:191: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:209: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:212: characters 19-20 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:221: characters 19-20 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:262: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:312: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:316: characters 19-20 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:325: characters 19-20 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:182: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes

E:\FNF Engines\Forever-Engine-Feather-master\Forever-Engine-Feather-master>lime test windows
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:94: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:142: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:150: characters 18-19 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:151: characters 18-19 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:413: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:419: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:420: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:423: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:424: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:426: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:427: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:429: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:429: characters 44-45 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:430: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:430: characters 44-45 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:450: characters 20-21 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:456: characters 20-21 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:493: characters 30-31 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:494: characters 30-31 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:191: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:209: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:212: characters 19-20 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:221: characters 19-20 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:262: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:312: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:316: characters 19-20 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:325: characters 19-20 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:182: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes

happens after downloading and compiling

**Comment by AltronMaxX** [comment]
Try to update all libraries, using ``haxelib update``

**Comment by BlazeTBV** [comment]
didnt do anything

**Comment by AltronMaxX** [comment]
Which version of flixel are you using?

**Comment by BlazeTBV** [comment]
5

**Comment by BeastlyGhost** [comment]
it's a flixel issue, uninstall flixel-addons with `haxelib remove flixel-addons` and install it again

**Comment by BlazeTBV** [comment]
but i did and that did nothing

**Comment by BlazeTBV** [comment]
im still having this issue
