### ISSUE TITLE
bug in the menu

### ISSUE THREAD

**Issue by liri1222335456** [BeastlyGhost/Forever-Engine-Feather#4]
i just pressed enter in the menu
![image](https://user-images.githubusercontent.com/95513575/200924172-237b9a9f-a714-4bf4-a883-3d637895e3d7.png)

**Comment by AltronMaxX** [comment]
Try to do this:
haxelib remove SScript

then

haxelib git SScript https://github.com/TheWorldMachinima/SScript

**Comment by BeastlyGhost** [comment]
yep, it's this ^
